#!/bin/sh

# See http://github.com/rentzsch/mogenerator

# Script path from: http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-in
SCRIPT_PATH="${BASH_SOURCE[0]}";
if([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
pushd . > /dev/null
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null


mogenerator --model $SCRIPT_PATH/../Resources/KegPad.xcdatamodeld/KegPad.xcdatamodel && mv _*.m _*.h $SCRIPT_PATH/../Classes/Models/ && rm *.m *.h
