#!/bin/sh

SCRIPT_PATH=$(cd `dirname $0` && pwd)
cd $SCRIPT_PATH
mogenerator --model $SCRIPT_PATH/../Resources/KegPad.xcdatamodeld/KegPad-2.xcdatamodel && mv _*.m _*.h $SCRIPT_PATH/../Classes/Models/ && rm *.m *.h
